env:
  secure: Xp+MekGKRm/PPAmKIbQLnw2Np6cVkyHMefrYL+P7u5XULWnGJM93FnC+k7ZcjrWklsXep3scYTotrmSAtJxIzV1mqDBZcWEbnqNTXpUicSB7YCStisiuTg9IN9mak+0adt6MWRC0wc3V3cXdDtJOm86hhsIg1lpCPF7HthvE/K5stcn4L5ul/JIsMbn8QyTH04+1//W2P7a7NiP0Y95GBuZ8vhY6QEdicPGNMeKc+bVSnlpWyrr9UAvJYR02yMyNIav/4mp2KEYZfqZHR7+O5xRKe4asS0Ut/cz+j2sOMNwNsxNWyYfViJg3Tl/M32dYW6DCviN8PlmnPw7uOGUCzMmZhRrIBliaBJYqI5Tkm+SoVnQcQn5weUjhee00Ofrit30PFVQQGruRMU2BLmLQp9NewvR6QoIySDFlztgDwYh7OWcdGIRTelrV82a/m88e9U5Sj6Pq2/SUkrtpjU2r5Vhc9rNUDvtKUQVuW1QrekQlmtAejlo1sspHqZRM61qWDVzBJPK3ytEfm1yMaTHyvP3hpYXRFN6hyP74P1P6GR77NeHFm7V1Dnv+W5emyrxxZsEA09KkX9cUDA6E7T7AJDlxxx3w/dk2WL5IWf1dCqrTIKPA64ZH3oVH8rkaSL/QXL72H/hNVuH2cWT+ApmOJF3r5cyYVK+DgKSRIHcR/8g=
language: ruby
rvm:
- 2.6.5
before_install:
- nvm install 12.13.1
before_script:
- npm install -g yarn@1.22.4
- bundle config set without production
- bundle config set path vendor/bundle
- bundle install
- yarn install
script:
- bundle exec rake db:drop
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec
- bundle exec cucumber
